CREATE TABLE [dbo].[DialogueSecurites]
(
	[Id] INT IDENTITY (1, 1) NOT NULL, 
    [Date] DATETIME NOT NULL, 
    [Contexte] NVARCHAR(MAX) NOT NULL, 
    [Observation] NVARCHAR(MAX) NOT NULL, 
    [Reflexion] NVARCHAR(MAX) NOT NULL, 
    [Action] NVARCHAR(MAX) NOT NULL, 
    [Atelier] NCHAR(10) NULL, 
    [SiteId] INT NOT NULL,
	[CompteurAnnuelSite] INT NOT NULL, 
    [Code] NVARCHAR(50) NOT NULL, 
    [ZoneId] INT NOT NULL, 
    [LieuId] INT NOT NULL, 
    [Dialogueur1Id] INT NOT NULL, 
    [Dialogueur2Id] INT NULL, 
    [Dialogueur3Id] INT NULL, 
    [Entretenu1Id] INT NOT NULL, 
    [Entretenu2Id] INT NULL, 
    [Entretenu3Id] INT NULL, 
    [ServiceTypeDialogueur1Id] INT NOT NULL, 
    [ServiceTypeDialogueur2Id] INT NULL, 
    [ServiceTypeDialogueur3Id] INT NULL, 
    [ServiceTypeEntretenu1Id] INT NOT NULL, 
    [ServiceTypeEntretenu2Id] INT NULL, 
    [ServiceTypeEntretenu3Id] INT NULL, 
    [ThematiqueId] INT NOT NULL, 
	CONSTRAINT [PK_dbo.DialogueSecurites] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_dbo.DialogueSecurites_dbo.Sites_SiteId] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[Sites] ([SiteID]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.Zones_ZoneId] FOREIGN KEY ([ZoneId]) REFERENCES [dbo].[Zones] ([ZoneID]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.Lieux_LieuId] FOREIGN KEY ([LieuId]) REFERENCES [dbo].[Lieux] ([LieuID]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.Thematiques_ThematiqueId] FOREIGN KEY ([ThematiqueId]) REFERENCES [dbo].[Thematiques] ([ThematiqueId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.PersonnesDialogueur1_PersonneId] FOREIGN KEY ([Dialogueur1Id]) REFERENCES [dbo].[Personnes] ([PersonneId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.PersonnesDialogueur2_PersonneId] FOREIGN KEY ([Dialogueur2Id]) REFERENCES [dbo].[Personnes] ([PersonneId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.PersonnesDialogueur3_PersonneId] FOREIGN KEY ([Dialogueur3Id]) REFERENCES [dbo].[Personnes] ([PersonneId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.PersonnesEntretenu1_PersonneId] FOREIGN KEY ([Entretenu1Id]) REFERENCES [dbo].[Personnes] ([PersonneId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.PersonnesEntretenu2_PersonneId] FOREIGN KEY ([Entretenu2Id]) REFERENCES [dbo].[Personnes] ([PersonneId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.PersonnesEntretenu3_PersonneId] FOREIGN KEY ([Entretenu3Id]) REFERENCES [dbo].[Personnes] ([PersonneId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.ServiceTypesDialogueur1_PersonneId] FOREIGN KEY ([ServiceTypeDialogueur1Id]) REFERENCES [dbo].[ServiceTypes]([ServiceTypeId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.ServiceTypesDialogueur2_PersonneId] FOREIGN KEY ([ServiceTypeDialogueur2Id]) REFERENCES [dbo].[ServiceTypes]([ServiceTypeId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.ServiceTypesDialogueur3_PersonneId] FOREIGN KEY ([ServiceTypeDialogueur3Id]) REFERENCES [dbo].[ServiceTypes]([ServiceTypeId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.ServiceTypesEntretenu1_PersonneId] FOREIGN KEY ([ServiceTypeEntretenu1Id]) REFERENCES [dbo].[ServiceTypes]([ServiceTypeId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.ServiceTypesEntretenu2_PersonneId] FOREIGN KEY ([ServiceTypeEntretenu2Id]) REFERENCES [dbo].[ServiceTypes]([ServiceTypeId]),
	CONSTRAINT [FK_dbo.DialogueSecurites_dbo.ServiceTypesEntretenu3_PersonneId] FOREIGN KEY ([ServiceTypeEntretenu3Id]) REFERENCES [dbo].[ServiceTypes]([ServiceTypeId]),


)
