//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public int ProjetID { get; set; }
        public string NomProjet { get; set; }
        public int StatutCouleur { get; set; }
        public int StatutVisage { get; set; }
        public string Commentaire { get; set; }
        public string ProchaineEtape { get; set; }
        public string DateOuverture { get; set; }
        public string DateCloture { get; set; }
        public string Service { get; set; }
    }
}
