//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Risque
    {
        public Risque()
        {
            this.FicheSecurites = new HashSet<FicheSecurite>();
        }
    
        public int RisqueId { get; set; }
        public string Nom { get; set; }
        public Nullable<int> RisqueTypeId { get; set; }

        [JsonIgnore]
        public virtual ICollection<FicheSecurite> FicheSecurites { get; set; }
        public virtual RisqueType RisqueType { get; set; }
    }
}
