//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauvegarde
    {
        public int SauvegardeID { get; set; }
        public string Site { get; set; }
        public double Date { get; set; }
        public float Volume { get; set; }
        public float Taux { get; set; }
        public int Duree { get; set; }
    }
}
