//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.FicheSecurites = new HashSet<FicheSecurite>();
            this.Lieux = new HashSet<Lieu>();
            this.PosteDeTravails = new HashSet<PosteDeTravail>();
        }
    
        public int ZoneID { get; set; }
        public int SiteId { get; set; }
        public int ZoneTypeId { get; set; }

        [JsonIgnore]
        public virtual ICollection<FicheSecurite> FicheSecurites { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites{ get; set; }
        [JsonIgnore]
        public virtual ICollection<Lieu> Lieux { get; set; }
        [JsonIgnore]
        public virtual ICollection<PosteDeTravail> PosteDeTravails { get; set; }
        public virtual Site Site { get; set; }
        public virtual ZoneType ZoneType { get; set; }
    }
}
