//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionSecurite
    {
        public int ActionSecuriteId { get; set; }
        public int FicheSecuriteId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string FaitPar { get; set; }
    
        public virtual FicheSecurite FicheSecurite { get; set; }
    }
}
