//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public Personne()
        {
            this.ActionQSEs = new HashSet<ActionQSE>();
            this.ActionQSEs1 = new HashSet<ActionQSE>();
            this.FicheSecurites1 = new HashSet<FicheSecurite>();
            this.FicheSecurites2 = new HashSet<FicheSecurite>();
            this.DialogueSecurites = new HashSet<DialogueSecurite>();
            this.DialogueSecurites1 = new HashSet<DialogueSecurite>();
            this.DialogueSecurites2 = new HashSet<DialogueSecurite>();
            this.DialogueSecurites3 = new HashSet<DialogueSecurite>();
            this.DialogueSecurites4 = new HashSet<DialogueSecurite>();
            this.DialogueSecurites5 = new HashSet<DialogueSecurite>();
        }
    
        public int PersonneId { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public System.Guid Guid { get; set; }

        [JsonIgnore]
        public virtual ICollection<ActionQSE> ActionQSEs { get; set; }
        [JsonIgnore]
        public virtual ICollection<ActionQSE> ActionQSEs1 { get; set; }
        [JsonIgnore]
        public virtual ICollection<FicheSecurite> FicheSecurites1 { get; set; }
        [JsonIgnore]
        public virtual ICollection<FicheSecurite> FicheSecurites2 { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites1 { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites2 { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites3 { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites4 { get; set; }
        [JsonIgnore]
        public virtual ICollection<DialogueSecurite> DialogueSecurites5 { get; set; }
    }
}
