//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Antelope.Domain.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.FicheSecurites = new HashSet<FicheSecurite>();
        }
    
        public int ServiceID { get; set; }
        public int SiteId { get; set; }
        public int ServiceTypeId { get; set; }

        [JsonIgnore]
        public virtual ICollection<FicheSecurite> FicheSecurites { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual Site Site { get; set; }
    }
}
